In [1]:
import pandas as pd
import feedparser

In [11]:
# Guardamos varias secciones del RSS de ESPN en un diccionario
secciones = {'general': 'https://www.espn.com/espn/rss/news',
    'nba': 'https://www.espn.com/espn/rss/nba/news',
    'nfl': 'https://www.espn.com/espn/rss/nfl/news',
    'mlb': 'https://www.espn.com/espn/rss/mlb/news'
}
lista_noticias = []

# Leemos cada feed con feedparser
for seccion, url in secciones.items():
    feed = feedparser.parse(url)
    
    for noticia in feed.entries:
        lista_noticias.append({
            'seccion': seccion,
            'titulo': noticia.title,
            'descripcion': noticia.description,
            'enlace': noticia.link,
            'fecha': noticia.published
        })

# Convertimos la lista en un dataframe de pandas
noticias_espn = pd.DataFrame(lista_noticias)

noticias_espn.head()

,seccion,titulo,descripcion,enlace,fecha
0,general,The biggest remaining roster hole for every NF...,"Even after free agency, trades and the draft, ...",https://www.espn.com/nfl/story/_/id/48649984/2...,"Thu, 7 May 2026 10:30:33 EST"
1,general,Who is on the hot seat after the draft? 14 vet...,Could Xavier Legette lose snaps to Chris Brazz...,https://www.espn.com/nfl/story/_/id/48675818/2...,"Thu, 7 May 2026 10:30:33 EST"
2,general,Sources: Rodgers likely to play for Steelers i...,Quarterback Aaron Rodgers is expected to visit...,https://www.espn.com/nfl/story/_/id/48703228/s...,"Thu, 7 May 2026 11:28:08 EST"
3,general,Haslam wants Giannis' future settled before draft,Bucks co-owner Jimmy Haslam says he would like...,https://www.espn.com/nba/story/_/id/48697585/b...,"Thu, 7 May 2026 11:28:08 EST"
4,general,Finch: Wolves 'got punked' in 38-point blowout,"The Timberwolves, despite a warning from super...",https://www.espn.com/nba/story/_/id/48700497/w...,"Thu, 7 May 2026 11:28:08 EST"

In [10]:
noticias_espn.to_csv('espn_rss_noticias.csv', encoding='UTF-8', index=False)

In [9]:
df_espn = pd.read_csv('espn_rss_noticias.csv', encoding='UTF-8')

df_espn

,seccion,titulo,descripcion,enlace,fecha
0,general,The biggest remaining roster hole for every NF...,"Even after free agency, trades and the draft, ...",https://www.espn.com/nfl/story/_/id/48649984/2...,"Thu, 7 May 2026 10:30:33 EST"
1,general,Who is on the hot seat after the draft? 14 vet...,Could Xavier Legette lose snaps to Chris Brazz...,https://www.espn.com/nfl/story/_/id/48675818/2...,"Thu, 7 May 2026 10:30:33 EST"
2,general,Sources: Rodgers likely to play for Steelers i...,Quarterback Aaron Rodgers is expected to visit...,https://www.espn.com/nfl/story/_/id/48703228/s...,"Thu, 7 May 2026 11:28:08 EST"
3,general,Haslam wants Giannis' future settled before draft,Bucks co-owner Jimmy Haslam says he would like...,https://www.espn.com/nba/story/_/id/48697585/b...,"Thu, 7 May 2026 11:28:08 EST"
4,general,Finch: Wolves 'got punked' in 38-point blowout,"The Timberwolves, despite a warning from super...",https://www.espn.com/nba/story/_/id/48700497/w...,"Thu, 7 May 2026 11:28:08 EST"
...,...,...,...,...,...
91,mlb,Olney: How Mike Trout changed this winter to r...,The Angels slugger is showing glimpses of his ...,https://www.espn.com/mlb/story/_/id/48677767/m...,"Wed, 6 May 2026 09:45:34 EST"
92,mlb,"Thank you, Pokémon: Zach Neto pulls rare Chari...",The shortstop didn't get a hit in five games u...,https://www.espn.com/mlb/story/_/id/48696712/l...,"Wed, 6 May 2026 18:41:10 EST"
93,mlb,"Fantasy baseball: Concerns for Tyler Glasnow, ...",All of the important fantasy spin and actionab...,https://www.espn.com/fantasy/baseball/story/_/...,"Thu, 7 May 2026 07:50:30 EST"
94,mlb,MLB awards: Ohtani and Judge continue to lead ...,Who are the favorites to win seasonlong honors...,https://www.espn.com/espn/betting/story/_/id/4...,"Thu, 7 May 2026 08:56:25 EST"
95,mlb,Every team's odds to win the 2026 World Series...,"As the Dodgers lead the way, the slumping Mets...",https://www.espn.com/espn/betting/story/_/id/4...,"Thu, 7 May 2026 08:56:25 EST"