In [4]:
!pip install pandas
!pip install feedparser

Requirement already satisfied: pandas in c:\users\alvar\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\alvar\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alvar\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\alvar\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\alvar\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: C:\Users\alvar\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ---------------------------------------- 0.0/81.5 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/81.5 kB ? eta -:--:--
   --------------- ------------------------ 30.7/81.5 kB 660.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.5 kB 495.5 kB/s eta 0:00:01
   ---------------------------------------- 81.5/81.5 kB 569.9 kB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (pyproject.toml): started
  Building wheel for sgmllib3k (pyproject.toml): finished with status 'done'
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6104 sha256=4c4f7f0abdb9b6e889c0bebafdef4cae5e85b7118e63d0d0c3c5b50606c076d5
  Stored in directory: c:\users\alvar\appdata\local\pip\cache\wheels\3b\25\2a\105d6a15df6914f4d15047691c6c28f9052cc1173e40285d03
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: C:\Users\alvar\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import feedparser

In [6]:
# Guardamos varias secciones del RSS de ESPN en un diccionario
secciones = {'general': 'https://www.espn.com/espn/rss/news',
    'nba': 'https://www.espn.com/espn/rss/nba/news',
    'nfl': 'https://www.espn.com/espn/rss/nfl/news',
    'mlb': 'https://www.espn.com/espn/rss/mlb/news'
}
lista_noticias = []

# Leemos cada feed con feedparser
for seccion, url in secciones.items():
    feed = feedparser.parse(url)
    
    for noticia in feed.entries:
        lista_noticias.append({
            'seccion': seccion,
            'titulo': noticia.title,
            'descripcion': noticia.description,
            'enlace': noticia.link,
            'fecha': noticia.published
        })

# Convertimos la lista en un dataframe de pandas
noticias_espn = pd.DataFrame(lista_noticias)

noticias_espn.head()

,seccion,titulo,descripcion,enlace,fecha
0,general,Takeaways from Thunder-Lakers Game 4,Here's what we've learned -- and what's next f...,https://www.espn.com/nba/story/_/id/48676289/2...,"Tue, 12 May 2026 02:05:06 EST"
1,general,LeBron: 'I don't know what the future holds',"LeBron James, whose record-setting 23rd season...",https://www.espn.com/nba/story/_/id/48747842/l...,"Tue, 12 May 2026 07:00:09 EST"
2,general,OKC escapes late L.A. charge to complete sweep,The Lakers refused to fold while facing elimin...,https://www.espn.com/nba/story/_/id/48747206/t...,"Tue, 12 May 2026 07:00:09 EST"
3,general,Bickerstaff calls FT disparity in loss 'unacce...,Pistons coach J.B. Bickerstaff called the gulf...,https://www.espn.com/nba/story/_/id/48747058/b...,"Tue, 12 May 2026 07:00:09 EST"
4,general,Mitchell's record-tying 2nd half evens East semis,Donovan Mitchell tied an NBA playoff record wi...,https://www.espn.com/nba/story/_/id/48746487/d...,"Tue, 12 May 2026 07:00:09 EST"

In [7]:
noticias_espn.to_csv('espn_rss_noticias.csv', encoding='UTF-8', index=False)

In [8]:
df_espn = pd.read_csv('espn_rss_noticias.csv', encoding='UTF-8')

df_espn

,seccion,titulo,descripcion,enlace,fecha
0,general,Takeaways from Thunder-Lakers Game 4,Here's what we've learned -- and what's next f...,https://www.espn.com/nba/story/_/id/48676289/2...,"Tue, 12 May 2026 02:05:06 EST"
1,general,LeBron: 'I don't know what the future holds',"LeBron James, whose record-setting 23rd season...",https://www.espn.com/nba/story/_/id/48747842/l...,"Tue, 12 May 2026 07:00:09 EST"
2,general,OKC escapes late L.A. charge to complete sweep,The Lakers refused to fold while facing elimin...,https://www.espn.com/nba/story/_/id/48747206/t...,"Tue, 12 May 2026 07:00:09 EST"
3,general,Bickerstaff calls FT disparity in loss 'unacce...,Pistons coach J.B. Bickerstaff called the gulf...,https://www.espn.com/nba/story/_/id/48747058/b...,"Tue, 12 May 2026 07:00:09 EST"
4,general,Mitchell's record-tying 2nd half evens East semis,Donovan Mitchell tied an NBA playoff record wi...,https://www.espn.com/nba/story/_/id/48746487/d...,"Tue, 12 May 2026 07:00:09 EST"
...,...,...,...,...,...
96,mlb,Who can keep the Dodgers from three-peating? W...,We make the case for the biggest threats to L....,https://www.espn.com/mlb/story/_/id/48702612/m...,"Sat, 9 May 2026 00:41:19 EST"
97,mlb,Free agent pickups: Waldschmidt and Snelling g...,The top players you should consider claiming o...,https://www.espn.com/fantasy/baseball/story/_/...,"Mon, 11 May 2026 11:31:33 EST"
98,mlb,Betts back for Dodgers and other Monday news t...,All of the important fantasy spin and actionab...,https://www.espn.com/fantasy/baseball/story/_/...,"Mon, 11 May 2026 11:31:33 EST"
99,mlb,Every team's odds to win the 2026 World Series...,Every MLB team's odds to win the 2026 World Se...,https://www.espn.com/espn/betting/story/_/id/4...,"Mon, 11 May 2026 14:49:02 EST"
100,mlb,"MLB awards: Ohtani, Judge continue to lead MVP...","Here are the odds for MVP, Cy Young and Rookie...",https://www.espn.com/espn/betting/story/_/id/4...,"Mon, 11 May 2026 14:49:02 EST"